/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventar;

import static java.lang.Integer.parseInt;
import static java.lang.String.valueOf;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author milosjelic
 */
public class RacunariFrame extends javax.swing.JFrame {

    Racunari racunar;
    Kategorija kategorija;
    Lokacija lokacija;
    Prijem prijem;
    int idKat;
    int idLok;
    int kol;
    String brfak;
    String naziv;
    String uneo;
    String datum;
    String napomena;

    /**
     * Creates new form RacunariPanel
     *
     * @param idKategorija
     * @param idLokacija
     * @param kolicina
     * @param brfakture
     * @param naziv
     * @param uneo
     * @param datum
     * @throws java.sql.SQLException
     */
    public RacunariFrame(int idKategorija, int idLokacija, int kolicina, String brfakture, String naziv, String napomena, String uneo, String datum) throws SQLException {
        initComponents();
        racunar = new Racunari();
        kategorija = new Kategorija();
        lokacija = new Lokacija();
        prijem = new Prijem(uneo, datum);
        idKat = idKategorija;
        idLok = idLokacija;
        kol = kolicina;
        brfak = brfakture;
        this.napomena = napomena;
        this.naziv = naziv;
        this.uneo = uneo;
        this.datum = datum;

        kategorijaLabel.setText(kategorija.getKategorija(idKategorija));
        ojLabel.setText(lokacija.getlokacija(idLokacija));
        kolicinaLabel.setText(valueOf(kolicina));
        nazivLabel.setText(naziv);
        uneoLabel.setText(uneo);
        datumLabel.setText(datum);
        fakturaLabel.setText(brfakture);
//        System.out.println(idKategorija);
//        System.out.println(idLokacija);
//        System.out.println(kolicina);
//        System.out.println(naziv);
//        System.out.println(uneo);
//        System.out.println(datum);

    }

    public RacunariFrame() {

    }

    class Data {

        String korisnik;
        String invBroj;
        String ipAdresa;
        String macAdresa;
        String os;
        String osKey;
        String office;
        String officeKey;
        String procesor;
        String ram;
        String hdd;
        String gpu;
        String napajanje;
        String specifikacija;

        public Data(String korisnik, String invBroj, String ipAdresa, String macAdresa, String os, String osKey, String office, String officeKey, String procesor, String ram, String hdd, String gpu, String napajanje, String specifikacija) {
            this.korisnik = korisnik;
            this.invBroj = invBroj;
            this.ipAdresa = ipAdresa;
            this.macAdresa = macAdresa;
            this.os = os;
            this.osKey = osKey;
            this.office = office;
            this.officeKey = officeKey;
            this.procesor = procesor;
            this.ram = ram;
            this.hdd = hdd;
            this.gpu = gpu;
            this.napajanje = napajanje;
            this.specifikacija = specifikacija;
        }
    }

    public Data getData() {
        // return person details from the method
        String procesor = procesorInput.getText();
        String ram = RAMInput.getText();
        String hdd = HDDInput.getText();
        String gpu = GPUInput.getText();
        String napajanje = PSUInput.getText();
        String specifikacija = racunar.specifikacija(procesor, ram, hdd, gpu, napajanje);
        String korisnik = korisnikInput.getText();
        String invBroj = invBrojInput.getText();
        String ipAdresa = ipAdresaInput.getText();
        String macAdresa = macAdresaInput.getText();
        String os = osComboBox.getSelectedItem().toString();
        String osKey = osKeyInput.getText();
        String office = officeComboBox.getSelectedItem().toString();
        String officeKey = officeKeyInput.getText();

        return new Data(korisnik, invBroj, ipAdresa, macAdresa, os, osKey, office, officeKey, procesor, ram, hdd, gpu, napajanje, specifikacija);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kategorijaLabel = new javax.swing.JLabel();
        ojLabel = new javax.swing.JLabel();
        nazivLabel = new javax.swing.JLabel();
        kolicinaLabel = new javax.swing.JLabel();
        uneoLabel = new javax.swing.JLabel();
        datumLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        fakturaLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        invBrojInput = new javax.swing.JTextField();
        ipAdresaInput = new javax.swing.JTextField();
        macAdresaInput = new javax.swing.JTextField();
        osComboBox = new javax.swing.JComboBox<>();
        osKeyInput = new javax.swing.JTextField();
        officeKeyInput = new javax.swing.JTextField();
        officeComboBox = new javax.swing.JComboBox<>();
        korisnikInput = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        procesorInput = new javax.swing.JTextField();
        RAMInput = new javax.swing.JTextField();
        HDDInput = new javax.swing.JTextField();
        GPUInput = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        PSUInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos računara");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Unos novog računara");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opšte informacije"));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Kategorija");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("OJ-Lokacija");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Naziv");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Količina");

        kategorijaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kategorijaLabel.setText("jLabel6");

        ojLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ojLabel.setText("jLabel7");

        nazivLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nazivLabel.setText("jLabel8");

        kolicinaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kolicinaLabel.setText("jLabel9");

        uneoLabel.setText("jLabel6");

        datumLabel.setText("jLabel7");

        jLabel20.setText("Broj fakture");

        fakturaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fakturaLabel.setText("jLabel21");

        jButton3.setText("<- Izmena/Povratak");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(uneoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datumLabel))
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ojLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nazivLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kolicinaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fakturaLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(kategorijaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kategorijaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ojLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nazivLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kolicinaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(fakturaLabel))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uneoLabel)
                    .addComponent(datumLabel)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodatne informacije"));

        jLabel6.setText("* Korisnik");

        jLabel7.setText("Inventarski broj");

        jLabel8.setText("* IP Adresa");

        jLabel9.setText("* MAC Adresa");

        jLabel10.setText("* Operativni sistem");

        jLabel11.setText("* OS Key");

        jLabel12.setText("* Office");

        jLabel13.setText("* Office Key");

        osComboBox.setMaximumRowCount(10);
        osComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Windows 98", "Windows XP", "Windows 7", "Windows 8", "Windows 10", "Windows 11", "Linux", "Ostalo" }));
        osComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                osComboBoxItemStateChanged(evt);
            }
        });

        officeComboBox.setMaximumRowCount(10);
        officeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "MS Office 2003", "MS Office 2007", "MS Office 2010", "MS Office 2013", "MS Office 2019", "MS Office 2021", "LibreOffice", "Ostalo" }));
        officeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                officeComboBoxItemStateChanged(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Specifikacija"));

        jLabel14.setText("Procesor");

        jLabel15.setText("RAM Memorija");

        jLabel16.setText("HDD/SSD");

        jLabel17.setText("Graficka kartica");

        HDDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HDDInputActionPerformed(evt);
            }
        });

        GPUInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPUInputActionPerformed(evt);
            }
        });

        jLabel19.setText("Napajanje");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(procesorInput)
                    .addComponent(RAMInput)
                    .addComponent(HDDInput)
                    .addComponent(GPUInput)
                    .addComponent(PSUInput))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(procesorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(RAMInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(HDDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(GPUInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(PSUInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jButton1.setText("Unesi");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jButton2.setText("Poništi");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });

        jLabel18.setText("Polja sa * su obavezna!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(korisnikInput)
                            .addComponent(invBrojInput)
                            .addComponent(ipAdresaInput)
                            .addComponent(macAdresaInput)
                            .addComponent(osComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(osKeyInput)
                            .addComponent(officeComboBox, 0, 150, Short.MAX_VALUE)
                            .addComponent(officeKeyInput))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(korisnikInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(invBrojInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ipAdresaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(macAdresaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(osComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(osKeyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(officeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(officeKeyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HDDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HDDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HDDInputActionPerformed

    private void GPUInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPUInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPUInputActionPerformed

    private void osComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_osComboBoxItemStateChanged
        String os = osComboBox.getSelectedItem().toString();
        if (os.equals("Ostalo") || os.equals("Linux")) {
            osKeyInput.setEnabled(false);
        } else {
            osKeyInput.setEnabled(true);
        }
    }//GEN-LAST:event_osComboBoxItemStateChanged

    private void officeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_officeComboBoxItemStateChanged
        String office = officeComboBox.getSelectedItem().toString();
        if (office.equals("LibreOffice") || office.equals("Ostalo")) {
            officeKeyInput.setEnabled(false);
        } else {
            officeKeyInput.setEnabled(true);
        }
    }//GEN-LAST:event_officeComboBoxItemStateChanged

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        this.dispose();
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        try {
            Data data = getData();
            boolean osKeyCheck;
            boolean officeKeyCheck;
            if (osKeyInput.isEnabled()) {
                osKeyCheck = data.osKey.isEmpty();
            } else {
                osKeyCheck = false;
            }
            if (officeKeyInput.isEnabled()) {
                officeKeyCheck = data.officeKey.isEmpty();
            } else {
                officeKeyCheck = false;
            }
            if (data.os.isEmpty() || data.os.equals(" ") || data.office.isEmpty() || data.ipAdresa.isEmpty() || data.macAdresa.isEmpty() || data.office.equals(" ") || osKeyCheck || officeKeyCheck) {
                JOptionPane.showMessageDialog(null, "Morate popuniti sva obavezna polja", "Greška", JOptionPane.ERROR_MESSAGE);
            } else if (racunar.checkInventarski(data.invBroj)) {
                JOptionPane.showMessageDialog(null, "Inventarski mora biti jedinstveni za svaki računar", "Greška", JOptionPane.ERROR_MESSAGE);
            } else if (racunar.checkIp(data.ipAdresa)) {
                JOptionPane.showMessageDialog(null, "IP Adresa mora biti jedinstvena za svaki računar", "Greška", JOptionPane.ERROR_MESSAGE);
            } else if (racunar.checkMAC(data.macAdresa)) {
                JOptionPane.showMessageDialog(null, "MAC Adresa mora biti jedinstvena za svaki računar", "Greška", JOptionPane.ERROR_MESSAGE);
            } else {
                Long idKey = racunar.add(idKat, idLok, data.invBroj, data.specifikacija, data.os, data.office, data.korisnik, data.ipAdresa, data.macAdresa, data.osKey, data.officeKey, uneo, datum);
                if (idKey != null) {
                    Integer idRacunar = idKey.intValue();
                    String brprijema = prijem.brojPrijema(datum, idKat, idLok);
                    if (prijem.addRacunar(brprijema, naziv, idKat, idLok, kol, idRacunar, brfak, uneo, datum, napomena, data.korisnik)) {
                        JOptionPane.showMessageDialog(null, "Uspešno ste uneli prijem računara!" + "\n" + brprijema, "Uspešno", JOptionPane.INFORMATION_MESSAGE);
                        new Prijem(uneo, datum).setVisible(true);
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(null, "Došlo je do greške, podaci nisu uneti!", "Greška", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Došlo je do greške, podaci nisu uneti!", "Greška", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(RacunariFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        procesorInput.setText(null);
        RAMInput.setText(null);
        HDDInput.setText(null);
        GPUInput.setText(null);
        PSUInput.setText(null);
        korisnikInput.setText(null);
        invBrojInput.setText(null);
        ipAdresaInput.setText(null);
        macAdresaInput.setText(null);
        osComboBox.setSelectedIndex(0);
        osKeyInput.setText(null);
        officeComboBox.setSelectedIndex(0);
        officeKeyInput.setText(null);

    }//GEN-LAST:event_jButton2MouseReleased


    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RacunariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RacunariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RacunariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RacunariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RacunariFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GPUInput;
    private javax.swing.JTextField HDDInput;
    private javax.swing.JTextField PSUInput;
    private javax.swing.JTextField RAMInput;
    private javax.swing.JLabel datumLabel;
    private javax.swing.JLabel fakturaLabel;
    private javax.swing.JTextField invBrojInput;
    private javax.swing.JTextField ipAdresaInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel kategorijaLabel;
    private javax.swing.JLabel kolicinaLabel;
    private javax.swing.JTextField korisnikInput;
    private javax.swing.JTextField macAdresaInput;
    private javax.swing.JLabel nazivLabel;
    private javax.swing.JComboBox<String> officeComboBox;
    private javax.swing.JTextField officeKeyInput;
    private javax.swing.JLabel ojLabel;
    private javax.swing.JComboBox<String> osComboBox;
    private javax.swing.JTextField osKeyInput;
    private javax.swing.JTextField procesorInput;
    private javax.swing.JLabel uneoLabel;
    // End of variables declaration//GEN-END:variables

}
