/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventar;

import java.awt.Component;
import static java.lang.Integer.valueOf;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author milosjelic
 */
public class ToneriPrijem extends javax.swing.JPanel {
    ToneriPregled tp;
    DefaultListModel<String> model;
    ArrayList existingToneri = new ArrayList<>();
    /**
     * Creates new form ToneriPrijem
     */
    public ToneriPrijem() {
        initComponents();
    }
    
    public ToneriPrijem(String username, String datum) throws SQLException {
        initComponents();
        tp = new ToneriPregled();
        model = new DefaultListModel<>();
        ArrayList<String> sviToneri = tp.getAllToneri();
        sviToneri.add(0,null);
        //sviToneri = tp.getAllToneri();
        toneriComboBox.setModel(new DefaultComboBoxModel<>(sviToneri.toArray(new String[0])));
        AutoCompleteDecorator.decorate(toneriComboBox);
        kolicinaSpin.setMinimum(1);
        kolicinaSpin.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        toneriList = new javax.swing.JList<>();
        prijemBtn = new javax.swing.JButton();
        ukloniBtn = new javax.swing.JButton();
        ukloniSveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        toneriComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        kolicinaSpin = new com.toedter.components.JSpinField();
        dodajBtn = new javax.swing.JButton();
        ponistiBtn = new javax.swing.JButton();
        prekidBtn = new javax.swing.JButton();

        toneriList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(toneriList);

        prijemBtn.setBackground(new java.awt.Color(204, 255, 204));
        prijemBtn.setText("Unesi");
        prijemBtn.setToolTipText("Unesi");

        ukloniBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ukloniBtn.setForeground(new java.awt.Color(255, 51, 51));
        ukloniBtn.setText("X");
        ukloniBtn.setToolTipText("Ukloni jedan");
        ukloniBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukloniBtnActionPerformed(evt);
            }
        });

        ukloniSveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ukloniSveBtn.setForeground(new java.awt.Color(255, 51, 51));
        ukloniSveBtn.setText("--");
        ukloniSveBtn.setToolTipText("Ukloni sve");
        ukloniSveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukloniSveBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Toneri Prijem");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodavanje tonera"));

        jLabel2.setText("Toner");

        jLabel3.setText("Količina");

        dodajBtn.setBackground(new java.awt.Color(204, 255, 204));
        dodajBtn.setText("Dodaj");
        dodajBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajBtnActionPerformed(evt);
            }
        });

        ponistiBtn.setBackground(new java.awt.Color(255, 153, 153));
        ponistiBtn.setText("Poništi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toneriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolicinaSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dodajBtn)
                    .addComponent(ponistiBtn))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(toneriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dodajBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(kolicinaSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ponistiBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        prekidBtn.setBackground(new java.awt.Color(255, 153, 153));
        prekidBtn.setText("Prekid");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(prijemBtn)
                                    .addGap(78, 78, 78)
                                    .addComponent(prekidBtn)
                                    .addGap(178, 178, 178))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ukloniBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ukloniSveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(ukloniBtn)
                        .addGap(18, 18, 18)
                        .addComponent(ukloniSveBtn)
                        .addGap(157, 157, 157))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prijemBtn)
                            .addComponent(prekidBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dodajBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajBtnActionPerformed
        String toner = toneriComboBox.getSelectedItem().toString();
        int kolicina = kolicinaSpin.getValue();
        
        for(int i=0; i<model.size(); i++){
            String listComponent = model.get(i);
            String[] toner2 = listComponent.split("Toner :");
            String[] toner3 = toner2[1].split(" ");
            String toner4 = toner3[1];
            if(!existingToneri.contains(toner4)){
            existingToneri.add(toner4);
            }
        }
        if(!existingToneri.contains(toner)){
            
        model.addElement("Toner : "+toner + " Kolicina : "+kolicina);
        }else{
            int index = existingToneri.indexOf(toner);
            String existingToner = model.get(index);
            String[] existingToner1 = existingToner.split("Kolicina :");
            String existingTonerFinal = existingToner1[1];
            int kolicina2 = Integer.valueOf(existingTonerFinal.trim()) + kolicina;
            model.remove(index);
            String input = "Toner : " + toner + " Kolicina : "+ kolicina2;
            model.add(index,input);
            
            
            
        }
        //System.out.println(existingToneri);
        toneriList.setModel(model);
    }//GEN-LAST:event_dodajBtnActionPerformed

    private void ukloniBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukloniBtnActionPerformed
        if(model.size() < 1){
           JOptionPane.showMessageDialog(toneriComboBox, "Lista je prazna");
       }else{
        int len = existingToneri.size();    
        int[] index = toneriList.getSelectedIndices();
            System.out.println(index.length);
         if(index.length > 0){
        Iterator itr = existingToneri.iterator();
        for( int i=0; i<len; i++) {

        itr.next();

        if ( index[i] >= 0) {

        itr.remove();
        model.removeElementAt(i);
        }

        }
            
 
        
         
         
        
         toneriList.setModel(model);
        }else{
          JOptionPane.showMessageDialog(toneriComboBox, "Morate izabrati element iz liste!", "Greška", JOptionPane.ERROR_MESSAGE);
        }}
        
    }//GEN-LAST:event_ukloniBtnActionPerformed

    private void ukloniSveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukloniSveBtnActionPerformed
       if(model.size() < 1){
           JOptionPane.showMessageDialog(toneriComboBox, "Lista je prazna");
       }else{
        int q = JOptionPane.showConfirmDialog(toneriComboBox,"Da li želite da izbrišete sve stavke", "Brisanje", JOptionPane.YES_NO_OPTION);
       if(q == 0){
        model.removeAllElements();
       existingToneri.removeAll(existingToneri);
       toneriList.setModel(model);
       }}
    }//GEN-LAST:event_ukloniSveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodajBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.components.JSpinField kolicinaSpin;
    private javax.swing.JButton ponistiBtn;
    private javax.swing.JButton prekidBtn;
    private javax.swing.JButton prijemBtn;
    private javax.swing.JComboBox<String> toneriComboBox;
    private javax.swing.JList<String> toneriList;
    private javax.swing.JButton ukloniBtn;
    private javax.swing.JButton ukloniSveBtn;
    // End of variables declaration//GEN-END:variables
}
